---
title: "Metodi di Psicofisiologia e Neuroimaging nella Clinica e nelle Neuroscienze Cognitive"
author: "Raffaele M Mazziotti, PhD"
institute: "University of Florence"
title-block: false
page-layout: full
resources:
  - quiz/
  - images/
  - docs/
format:
  revealjs:
    controls: true
    theme: default
    slide-number: false
    logo: images/logo/NEUROFARBA_logo.svg
    css: slide_style.css
    transition: fade
    center: true
    math: mathjax
    chalkboard: 
      buttons: false
    progress: true
    title-slide-attributes:
      data-background-image: images/logo/NEUROFARBA.svg
      data-background-size: 500px
      data-background-position: "center 10%"
    mermaid:
      theme: neutral
---

## Index

>[Welcome to the course!]{.highlight}
We will explore intrinsic optical imaging, fNIRS, pupillometry, and data-driven biomarker discovery, combining physiological principles with statistical and machine learning approaches for translational research.


### Chapters
::: columns
::: column

:::{.list-box}
- [Intrinsic Signals](2_instrinsic_signals.html)
- [Pupillometry](3_pupillometry.html)
- [Biomarkers](1_biomarkers.html)
:::

::: 
::: column

:::{.list-box}
- [Translational Biomarkers](4_translational_biomarkers.html)
- [Biomarker Data Mining](5_data_mining.html)
:::

:::
:::

## How to use these slides

::: columns
::: column

::: {.info-box}
[⛵ Navigation]{.highlight}

- These slides are **interactive**
- Use **keyboard** or **mouse**
- Press `F` for **full-screen mode**
:::

:::card
[⏱️ Quick access]{.highlight}

- In the **lower-left corner**, click the ☰ icon to open the **slide index**
- Click any slide title to jump directly to it
- Use the ⚙️ **Tools** menu to see all available shortcuts
:::

:::
::: column

::: {.info-box}
[🧭 Course structure]{.highlight}

- The **Index slide** links all sections
- Each section starts with a title slide
- A **🏠 Home button** on the first slide  
  brings you back to the Index
:::

::: {.card}
[📄 PDF version]{.highlight}

- Go to the **first slide of a section**
- Press `E`
- A **PDF-compatible version** appears
- Print or save it for clean notes
:::

:::
:::
